### PR TITLE
Add ldapchai 0.7.6 and 0.8.0

### PR DESCRIPTION
**Pull request by adangel**
Tried to reproduce https://repo.maven.apache.org/maven2/com/github/ldapchai/ldapchai/0.7.6/ldapchai-0.7.6.pom (Refs #42)

There are differences in META-INF/MANIFEST.MF, e.g. 

```diff
-Implementation-Build-Java-Vendor: AdoptOpenJDK
-Implementation-Build-Java-Version: 15
+Implementation-Build-Java-Vendor: Oracle Corporation
+Implementation-Build-Java-Version: 15.0.1
```

Should we try to match the exact JVM Vendor+Version when reproducing or should the project rather use "java.specification.version" (which is in this example 15)?

There is one other change:

```diff
-SCM-Git-Branch: master
+SCM-Git-Branch: 338023a44e4dc62aff8985ca42c2f6743258b1c0
```

This probably must be fixed by the project - using "master" here won't work, since when reproducing, master might point already to a later commit. Is this assumption correct?

I would create then an issue/PR upstream...

<details>
  <summary>ldapchai-0.7.6.jar</summary>
  <p>

```diff
--- target/reference/ldapchai-0.7.6.jar
+++ target/ldapchai-0.7.6.jar
├── zipinfo {}
│ @@ -1,9 +1,9 @@
│  Zip file size: 709683 bytes, number of entries: 432
│ --rw-r--r--  2.0 unx      732 b- defN 20-Aug-20 03:44 META-INF/MANIFEST.MF
│ +-rw-r--r--  2.0 unx      772 b- defN 20-Aug-20 03:44 META-INF/MANIFEST.MF
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/com/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/com/novell/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/cr/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/cr/bean/
│ @@ -427,8 +427,8 @@
│  -rw-r--r--  2.0 unx     1810 b- defN 20-Aug-20 03:44 com/novell/ldapchai/util/SearchHelper$FilterSequence.class
│  -rw-r--r--  2.0 unx    12002 b- defN 20-Aug-20 03:44 com/novell/ldapchai/util/SearchHelper.class
│  -rw-r--r--  2.0 unx     4917 b- defN 20-Aug-20 03:44 com/novell/ldapchai/util/StringHelper.class
│  -rw-r--r--  2.0 unx     1085 b- defN 20-Aug-20 03:44 com/novell/ldapchai/util/Uint32Charset$Uint32CharsetDecoder.class
│  -rw-r--r--  2.0 unx     1083 b- defN 20-Aug-20 03:44 com/novell/ldapchai/util/Uint32Charset.class
│  -rw-r--r--  2.0 unx    27793 b- defN 20-Aug-20 03:44 META-INF/maven/com.github.ldapchai/ldapchai/pom.xml
│  -rw-r--r--  2.0 unx       62 b- defN 20-Aug-20 03:44 META-INF/maven/com.github.ldapchai/ldapchai/pom.properties
│ -432 files, 1912431 bytes uncompressed, 626851 bytes compressed:  67.2%
│ +432 files, 1912471 bytes uncompressed, 626851 bytes compressed:  67.2%
├── META-INF/MANIFEST.MF
│ @@ -1,20 +1,20 @@
│  Manifest-Version: 1.0
│  Created-By: Maven Jar Plugin 3.2.0
│  Build-Jdk-Spec: 14
│  Main-Class: com.novell.ldapchai.util.MainHandler
│  Archive-Type: jar
│  Archive-UID: 854FF0D1B8B9E20E9476A6658AEF997E0ACB09ED6F9B593E086D2C8FBD8
│   3DBA8
│ -Implementation-Build-Java-Vendor: AdoptOpenJDK
│ +Implementation-Build-Java-Vendor: Oracle Corporation
│  Implementation-Build-Java-Version: 14.0.2
│  Implementation-Title: LDAP Chai Library
│  Implementation-URL: https://github.com/ldapchai/ldapchai
│  Implementation-Vendor: LDAP Chai Project
│  Implementation-Version: 0.7.6
│ -SCM-Git-Branch: master
│ +SCM-Git-Branch: 142831748eaff44477142ac121e34a2f2b94e19d
│  SCM-Git-Commit-Dirty: false
│  SCM-Git-Commit-ID: 142831748eaff44477142ac121e34a2f2b94e19d
│  SCM-Git-Commit-ID-Abbrev: 1428317
│  SCM-Git-Commit-ID-Description: 1428317
│  SCM-Git-Commit-Timestamp: 2020-08-20T03:44:41Z
```

</p>
</details>

<details>
  <summary>ldapchai-0.7.6-sources.jar</summary>
  <p>

```diff
--- target/reference/ldapchai-0.7.6-sources.jar
+++ target/ldapchai-0.7.6-sources.jar
├── zipinfo {}
│ @@ -1,9 +1,9 @@
│ -Zip file size: 587964 bytes, number of entries: 356
│ --rw-r--r--  2.0 unx      581 b- defN 20-Aug-20 03:44 META-INF/MANIFEST.MF
│ +Zip file size: 587963 bytes, number of entries: 356
│ +-rw-r--r--  2.0 unx      621 b- defN 20-Aug-20 03:44 META-INF/MANIFEST.MF
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 META-INF/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/novell/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/novell/ldapchai/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/novell/ldapchai/cr/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/novell/ldapchai/cr/bean/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Aug-20 03:44 com/novell/ldapchai/exception/
│ @@ -351,8 +351,8 @@
│  -rw-r--r--  2.0 unx     4818 b- defN 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/util/SCryptUtil.java
│  -rw-r--r--  2.0 unx    22078 b- defN 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/util/SearchHelper.java
│  -rw-r--r--  2.0 unx     6547 b- defN 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/util/StringHelper.java
│  -rw-r--r--  2.0 unx     2074 b- defN 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/util/Uint32Charset.java
│  -rw-r--r--  2.0 unx      932 b- defN 20-Aug-20 03:44 META-INF/source/com/novell/ldapchai/util/package-info.java
│  -rw-r--r--  2.0 unx    27793 b- defN 20-Aug-20 03:44 META-INF/maven/com.github.ldapchai/ldapchai/pom.xml
│  -rw-r--r--  2.0 unx       62 b- defN 20-Aug-20 03:44 META-INF/maven/com.github.ldapchai/ldapchai/pom.properties
│ -356 files, 2080648 bytes uncompressed, 521210 bytes compressed:  75.0%
│ +356 files, 2080688 bytes uncompressed, 521209 bytes compressed:  75.0%
├── META-INF/MANIFEST.MF
│ @@ -1,16 +1,16 @@
│  Manifest-Version: 1.0
│  Created-By: Maven Source Plugin 3.2.1
│  Archive-Type: source
│ -Implementation-Build-Java-Vendor: AdoptOpenJDK
│ +Implementation-Build-Java-Vendor: Oracle Corporation
│  Implementation-Build-Java-Version: 14.0.2
│  Implementation-Title: LDAP Chai Library
│  Implementation-URL: https://github.com/ldapchai/ldapchai
│  Implementation-Vendor: LDAP Chai Project
│  Implementation-Version: 0.7.6
│ -SCM-Git-Branch: master
│ +SCM-Git-Branch: 142831748eaff44477142ac121e34a2f2b94e19d
│  SCM-Git-Commit-Dirty: 
│  SCM-Git-Commit-ID: 142831748eaff44477142ac121e34a2f2b94e19d
│  SCM-Git-Commit-ID-Abbrev: 1428317
│  SCM-Git-Commit-ID-Description: 1428317
│  SCM-Git-Commit-Timestamp: 2020-08-20T03:44:41Z
```

</p>
</details>

<details>
  <summary>ldapchai-0.8.0.jar</summary>
  <p>

```diff
--- target/reference/ldapchai-0.8.0.jar
+++ target/ldapchai-0.8.0.jar
├── zipinfo {}
│ @@ -1,9 +1,9 @@
│ -Zip file size: 711369 bytes, number of entries: 432
│ --rw-r--r--  2.0 unx      728 b- defN 20-Oct-13 14:19 META-INF/MANIFEST.MF
│ +Zip file size: 711372 bytes, number of entries: 432
│ +-rw-r--r--  2.0 unx      772 b- defN 20-Oct-13 14:19 META-INF/MANIFEST.MF
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/com/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/com/novell/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/cr/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/cr/bean/
│ @@ -427,8 +427,8 @@
│  -rw-r--r--  2.0 unx     1810 b- defN 20-Oct-13 14:19 com/novell/ldapchai/util/SearchHelper$FilterSequence.class
│  -rw-r--r--  2.0 unx    12002 b- defN 20-Oct-13 14:19 com/novell/ldapchai/util/SearchHelper.class
│  -rw-r--r--  2.0 unx     4917 b- defN 20-Oct-13 14:19 com/novell/ldapchai/util/StringHelper.class
│  -rw-r--r--  2.0 unx     1085 b- defN 20-Oct-13 14:19 com/novell/ldapchai/util/Uint32Charset$Uint32CharsetDecoder.class
│  -rw-r--r--  2.0 unx     1083 b- defN 20-Oct-13 14:19 com/novell/ldapchai/util/Uint32Charset.class
│  -rw-r--r--  2.0 unx    27659 b- defN 20-Oct-13 14:19 META-INF/maven/com.github.ldapchai/ldapchai/pom.xml
│  -rw-r--r--  2.0 unx       62 b- defN 20-Oct-13 14:19 META-INF/maven/com.github.ldapchai/ldapchai/pom.properties
│ -432 files, 1916712 bytes uncompressed, 628537 bytes compressed:  67.2%
│ +432 files, 1916756 bytes uncompressed, 628540 bytes compressed:  67.2%
├── META-INF/MANIFEST.MF
│ @@ -1,20 +1,20 @@
│  Manifest-Version: 1.0
│  Created-By: Maven Jar Plugin 3.2.0
│  Build-Jdk-Spec: 15
│  Main-Class: com.novell.ldapchai.util.MainHandler
│  Archive-Type: jar
│  Archive-UID: 854FF0D1B8B9E20E9476A6658AEF997E0ACB09ED6F9B593E086D2C8FBD8
│   3DBA8
│ -Implementation-Build-Java-Vendor: AdoptOpenJDK
│ -Implementation-Build-Java-Version: 15
│ +Implementation-Build-Java-Vendor: Oracle Corporation
│ +Implementation-Build-Java-Version: 15.0.1
│  Implementation-Title: LDAP Chai Library
│  Implementation-URL: https://github.com/ldapchai/ldapchai
│  Implementation-Vendor: LDAP Chai Project
│  Implementation-Version: 0.8.0
│ -SCM-Git-Branch: master
│ +SCM-Git-Branch: 338023a44e4dc62aff8985ca42c2f6743258b1c0
│  SCM-Git-Commit-Dirty: false
│  SCM-Git-Commit-ID: 338023a44e4dc62aff8985ca42c2f6743258b1c0
│  SCM-Git-Commit-ID-Abbrev: 338023a
│  SCM-Git-Commit-ID-Description: 338023a
│  SCM-Git-Commit-Timestamp: 2020-10-13T14:19:10Z
```

</p>
</details>

<details>
  <summary>ldapchai-0.8.0-sources.jar</summary>
  <p>

```diff
--- target/reference/ldapchai-0.8.0-sources.jar
+++ target/ldapchai-0.8.0-sources.jar
├── zipinfo {}
│ @@ -1,9 +1,9 @@
│ -Zip file size: 588973 bytes, number of entries: 356
│ --rw-r--r--  2.0 unx      577 b- defN 20-Oct-13 14:19 META-INF/MANIFEST.MF
│ +Zip file size: 588975 bytes, number of entries: 356
│ +-rw-r--r--  2.0 unx      621 b- defN 20-Oct-13 14:19 META-INF/MANIFEST.MF
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 META-INF/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/novell/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/novell/ldapchai/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/novell/ldapchai/cr/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/novell/ldapchai/cr/bean/
│  drwxr-xr-x  2.0 unx        0 b- stor 20-Oct-13 14:19 com/novell/ldapchai/exception/
│ @@ -351,8 +351,8 @@
│  -rw-r--r--  2.0 unx     4818 b- defN 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/util/SCryptUtil.java
│  -rw-r--r--  2.0 unx    22078 b- defN 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/util/SearchHelper.java
│  -rw-r--r--  2.0 unx     6547 b- defN 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/util/StringHelper.java
│  -rw-r--r--  2.0 unx     2074 b- defN 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/util/Uint32Charset.java
│  -rw-r--r--  2.0 unx      932 b- defN 20-Oct-13 14:19 META-INF/source/com/novell/ldapchai/util/package-info.java
│  -rw-r--r--  2.0 unx    27659 b- defN 20-Oct-13 14:19 META-INF/maven/com.github.ldapchai/ldapchai/pom.xml
│  -rw-r--r--  2.0 unx       62 b- defN 20-Oct-13 14:19 META-INF/maven/com.github.ldapchai/ldapchai/pom.properties
│ -356 files, 2083200 bytes uncompressed, 522219 bytes compressed:  74.9%
│ +356 files, 2083244 bytes uncompressed, 522221 bytes compressed:  74.9%
├── META-INF/MANIFEST.MF
│ @@ -1,16 +1,16 @@
│  Manifest-Version: 1.0
│  Created-By: Maven Source Plugin 3.2.1
│  Archive-Type: source
│ -Implementation-Build-Java-Vendor: AdoptOpenJDK
│ -Implementation-Build-Java-Version: 15
│ +Implementation-Build-Java-Vendor: Oracle Corporation
│ +Implementation-Build-Java-Version: 15.0.1
│  Implementation-Title: LDAP Chai Library
│  Implementation-URL: https://github.com/ldapchai/ldapchai
│  Implementation-Vendor: LDAP Chai Project
│  Implementation-Version: 0.8.0
│ -SCM-Git-Branch: master
│ +SCM-Git-Branch: 338023a44e4dc62aff8985ca42c2f6743258b1c0
│  SCM-Git-Commit-Dirty: 
│  SCM-Git-Commit-ID: 338023a44e4dc62aff8985ca42c2f6743258b1c0
│  SCM-Git-Commit-ID-Abbrev: 338023a
│  SCM-Git-Commit-ID-Description: 338023a
│  SCM-Git-Commit-Timestamp: 2020-10-13T14:19:10Z
```

### CODE REVIEW

**Comment by hboutemy** [comment]
thank you @adangel 
on Implementation-Build-Java-Vendor, IMHO, we should propose them to avoid such field: given we can reproduce the same binary with any JDK (with the right major version), such precision in MANIFEST.MF just adds complexity to Reproducible Builds

on SCM configuration, same logic: does the branch really add value?

if you created an issue at upstream project, don't hesitate to point to it in your buildspec

**Comment by hboutemy** [comment]
notice: I'll probably merge this PR as is because it seems the sad reality is that these releases are not reproducible
pointing to an issue to upstream project is our best bet to hope that reproducibility issues will be fixed for next public release

**Comment by adangel** [comment]
I've added the reference to the upstream issue: https://github.com/ldapchai/ldapchai/pull/24

**Comment by hboutemy** [comment]
great job, thank you

**Pull request merged**
