### PR TITLE
auto-record groupId changed

### PR DESCRIPTION
**Pull request by pawellabaj**
Created new buildspec after groupId changed

I'm facing problems with building in Podman - see pawellabaj/auto-record#133

### CODE REVIEW

**Comment by hboutemy** [comment]
please don't remove history: history remains, even if in a now defunct groupId
I just did the groupId update for release 3.0.0 in 8b7718e74bbc7734d1bcde50b02043b0327caee2

I also published release 3.1.0

I proposed you https://github.com/pawellabaj/auto-record/pull/134 to configure skip deploy in a more classical way

on your issue with podman, are you sure the right Maven version is used?

**Comment by pawellabaj** [comment]
Thanks for proposed changes in pom.

As to build issues, I tried default maven and the latest - "mvn-3.9.5" - and I got the same issues

**Comment by pawellabaj** [comment]
@hboutemy , how to ignore some artifacts in `.buildspec`? 
I don't plan to release test or doc artifacts

**Comment by hboutemy** [comment]
with PR merged, it should be automatic
without PR merged, it requires a new maven-artifact-plugin release because of https://issues.apache.org/jira/browse/MARTIFACT-52

**Comment by hboutemy** [comment]
as you can see, 3.1.1 is ok https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/pl/com/labaj/autorecord/auto-record/README.md
at least i can rebuild it: is it ok to you?

**Comment by pawellabaj** [comment]
It's ok

Thank you @hboutemy for help

**Pull request closed without merging**
