### PR TITLE
add ratis-thirdparty 1.0.7

### PR DESCRIPTION
**Pull request by adoroszlai**

### CODE REVIEW

**Comment by adoroszlai** [comment]
I get the same problem locally, SHA3 hashes are missing from SBOM generated by `cyclonedx-maven-plugin`.

```
│ -          <hash alg="SHA3-384">0fe16a47cf7aab0b22251dafcc39939b68e8f1778093309d8d2060b51a08df445a8b8ed5a9561669faf2e55f907c76d8</hash>
│ -          <hash alg="SHA3-256">3e5a1eb5ab7d0797498862794709ff8eaaa071fe4cc9ec77f52db7e2f97ef487</hash>
│ -          <hash alg="SHA3-512">59281a3e29e76270d7f44b40b5b9f05e55f1ae3ec716d80add806f360940809e3813998ac7c5758043b8e248aed73b86e37dc506cdb4cde03c16bb617d8e5a3a</hash>
```

**Comment by hboutemy** [comment]
release was done with Azul JDK 8, which has more hash algorithms than base OpenJDK 8
this edge case is configured by adding `jdkForceAzul=true` in buildspec

**Comment by adoroszlai** [comment]
Thanks @hboutemy for the info.

On a related note, should I squash my commits (and force-push) next time?

**Comment by hboutemy** [comment]
no need to do anything precise at Git level: it's not code tracking, where history is really important

another key aspect: once your project is initialized (and particularly when it is fully reproducible), I have daily automation that rebuild new releases: you won't need to check for it nor add a PR, I'll do (for more details, you can have a look at my intermediate page for that automation https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/doc/add.md )

then this question happens only on projects starting Reproducible Builds journey only

**Comment by adoroszlai** [comment]
nice, thank you

**Pull request merged**
