### PR TITLE
Buildspec dropwizard 2.0.11, 12, 13 include fix for `badDate` in repo history

### LINKED ISSUE #22: create buildspec for dropwizard 2.0.11 & 2.0.12
io.dropwizard:dropwizard-project:2.0.11

buildspec probably quite similar to release 2.0.10: let's hope build result reproducibility has improved on the last non-reproducible artifact

### PR DESCRIPTION
**Pull request by bhamail**
This PR builds on the one from @dialaya: https://github.com/jvm-repo-rebuild/reproducible-central/commit/52568e7593318bb8c36d13fe3602322792aaed99
The `.buildinfo.compare` files in this PR are identical to those in the PR from @dialaya. (versions 2.0.11, 2.0.12).
I added a new `.buildinfo.compare` file for version 2.0.13.

The main difference in my PR is an added fix for a corruption in the history of the origin repo (`badDate`) by telling git `fsck` to skip the corrupted commit.

This corruption will not be visible if you already have the origin repo cloned into your local `buildcache` dir. You would need to delete the `buildcache` dir (and ensure you have not configured git to globally skip fsck objects) in order to see the `badDate` issue.

I used a similar approach in PR #38, so we may want to update the current PR with any improvements from that one. 

Also Fixes #22

### CODE REVIEW

**Comment by hboutemy** [comment]
what version of Git are you using? or what configuration?
I'm using 2.25.1 and I get no issue with the repo: I'm not convinced about adding the workaround

**Comment by bhamail** [comment]
> what version of Git are you using? or what configuration?
> I'm using 2.25.1 and I get no issue with the repo: I'm not convinced about adding the workaround
```
$ git --version
git version 2.28.0
```

**Comment by hboutemy** [comment]
Git 2.28: wow, near latest and greatest now that 2.29 is out
I hope Git won't get picky like this, because it will break usage for many people
Did you try if Git 2.29 is a little less picky?

**Comment by bhamail** [comment]
@hboutemy FWIW, it appears git 2.29.2 has the same behavior regarding corrupt history:

```
$ git version
git version 2.29.2
```

(Delete `buildcache` dir between each attempt, to be sure we use a clean tree.)

Same failure using latest `master` branch:
```
$ ./rebuild.sh content/io/dropwizard/core/dropwizard-2.0.13.buildspec 
Rebuilding from spec content/io/dropwizard/core/dropwizard-2.0.13.buildspec
- groupId: io.dropwizard
- artifactId: dropwizard-core
- version: 2.0.13
- gitRepo: https://github.com/dropwizard/dropwizard.git
- gitTag: v2.0.13
- tool: mvn
- jdk: 8
- newline: lf
- command: mvn clean package -DskipTests
- buildinfo: dropwizard-archetypes/java-simple/target/java-simple-2.0.13.buildinfo
Cloning into 'dropwizard-core'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (195/195), done.
error: object 6fbf9def0293986beb2547a671f46148a5d2faf7: badDate: invalid author/committer line - bad date
fatal: fsck error in packed object
fatal: failed to clone dropwizard-core
```

Using branch `buildspec-dropwizard-2.0.11-12-13`:
```
$ ./rebuild.sh content/io/dropwizard/core/dropwizard-2.0.13.buildspec 
Rebuilding from spec content/io/dropwizard/core/dropwizard-2.0.13.buildspec
- groupId: io.dropwizard
- artifactId: dropwizard-core
- version: 2.0.13
- gitRepo: -c fetch.fsck.skipList=../gitFsckSkipList https://github.com/dropwizard/dropwizard.git
- gitTag: v2.0.13
- tool: mvn
- jdk: 8
- newline: lf
- command: mvn clean package -DskipTests
- buildinfo: dropwizard-archetypes/java-simple/target/java-simple-2.0.13.buildinfo
Cloning into 'dropwizard-core'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 220490 (delta 106), reused 118 (delta 21), pack-reused 220256
Receiving objects: 100% (220490/220490), 99.80 MiB | 14.11 MiB/s, done.
Resolving deltas: 100% (147733/147733), done.
Note: switching to 'v2.0.13'.

You are in 'detached HEAD' state. You can look around, make experimental
....chugs happily away
```

**Comment by hboutemy** [comment]
thank you @bhamail for checking
probably this should be reported to Dropwizard project, given this will affect their developers in the future for their basic development

**Comment by bhamail** [comment]
Reported the git history corruption issue to dropwizard here: https://github.com/dropwizard/dropwizard/issues/3563

**Comment by bhamail** [comment]
From the comments in https://github.com/dropwizard/dropwizard/issues/3563, it appears such historical data corruption issues can not be repaired without in validating everything after that point in the repo. That said, we may have to "deal" with such corruption when newer git clients become the norm. I'm guessing we'll need to support a list of hashes to ignore, a la `gitFsckSkipList`. Maybe now is the time to update the scripts to support such a skip list, rather than the sneaky approach I took of adding it on...or not. Your call, but I don't think this issue will go away.

**Comment by bhamail** [comment]
This [helpful comment](https://github.com/dropwizard/dropwizard/issues/3563#issuecomment-806803485) has me thinking the script could be altered to turn off the `fsckobjects`(thereby avoiding the need for global git config changes)?

**Comment by hboutemy** [comment]
I still don't know how your are affected but not others :)
I prefer this "`fsckobjects` off" idea, instead of the complex listing of offending commits in `gitFsckSkipList` (hard to maintain)

on how to inject to the script, is it safe to blindly to off fsck in the script, for absolutely every Git repo?
Or should we add an optional entry in .buildspec to activate it only on the problematic Git repos (that should not happen often)?

Notice: current idea of putting the git command option in the git entry breaks the script that generates HTML output (because the entry was not expected to have multiple parts)

**Comment by bhamail** [comment]
I think the underlying reason I am "special" (and why others are not seeing this issue when repo history has corruptions)  is I am using a newer version of git `git version 2.29.2`, and I made no changes to any default global settings along the way. Also have to be sure to delete any cached checkout to trigger the issue (I chased my tail due to that a few times).

I agree changing the checkout command to skip `fsckobjects` is much better than my original workaround (which felt dirty from the start).

**Pull request closed without merging**
