### PR TITLE
Update Maven version for Error Prone Support builds

### PR DESCRIPTION
**Pull request by Stephan202**
This is in preparation for the upcoming release, which will require a more recent version of Maven.

(I suppose I could have updated only `error-prone-support-0.14.0.buildspec`, but I updated each `*.buildspec` to reference the latest Maven version supported.)

### CODE REVIEW

**Comment by hboutemy** [comment]
it's not really useful to update old recipes: update will be done on next release for the release that requires it

**Comment by Stephan202** [comment]
@hboutemy so you prefer a workflow where the script that picks up releases initially fails? I'm not tracking this project all the time, so it might be a while before I notice. (I assume you're not manually debugging this kind of issue for all projects currently tracked. :thinking:)

Not a problem to not merge this PR, but let me try my luck:
1. WDYT of merging this PR, and I'll promise to only update new releases next time?
2. Alternatively, WDYT of reducing this PR's scope to just updating the latest release (0.14.0)? I can push a commit for that.

**Comment by hboutemy** [comment]
rebuild is done by a human = me, just detection of what to rebuild is automated
I don't want to change all the history of past releases: yes, updating only the latest release is reasonable and will help me not needing to build twice when I discover that prerequisites were updated for the next release

**Comment by Stephan202** [comment]
Ack! I updated the branch to only contain this change:
```
diff --git a/content/tech/picnic/error-prone-support/error-prone-support/error-prone-support-0.14.0.buildspec b/content/tech/picnic/error-prone-support/error-prone-support/error-prone-support-0.14.0.buildspec
index bfa7befb..a6eeb22b 100644
--- a/content/tech/picnic/error-prone-support/error-prone-support/error-prone-support-0.14.0.buildspec
+++ b/content/tech/picnic/error-prone-support/error-prone-support/error-prone-support-0.14.0.buildspec
@@ -7,7 +7,7 @@ display=${groupId}:${artifactId}
 gitRepo=https://github.com/PicnicSupermarket/${artifactId}.git
 gitTag=v${version}
 
-tool=mvn-3.9.1
+tool=mvn-3.9.6
 jdk=17
 newline=lf
 
```

**Comment by hboutemy** [comment]
thank you

**Pull request merged**
