### PR TITLE
[project] Add Yupiik Tools Maven 1.2.5

### PR DESCRIPTION
**Pull request by fpapon**

### CODE REVIEW

**Comment by hboutemy** [comment]
FYI, running 
```
bin/add-new-release.sh content/io/yupiik/maven/plugin/yupiik-tools-maven-plugin-1.2.4.buildspec 1.2.5
```
prepares the new buildspec and gives you commands to copy/paste to create branch and PR

the PR will contain a link to https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/yupiik/maven/plugin/README.md which helps tracking if the new release is better or worse that the previous one

and "cherry on the cake" :) if your project's latest release, I do the new rebuild systematically without any request from the project

when the latest release is not fully reproducible, I crebuild the new release only when I decide (because I think it's worth it), a little bit later than the new releases of fully reproducible projects

**Comment by hboutemy** [comment]
this buldspec uses wrong JDK 

```
├── META-INF/MANIFEST.MF
│ @@ -1,4 +1,4 @@
│  Manifest-Version: 1.0
│  Created-By: Maven JAR Plugin 3.4.2
│ -Build-Jdk-Spec: 21
│ +Build-Jdk-Spec: 17
```

I'll create a new PR with the classical `add-new-release.sh` script, as it detects JDK automatically

**Comment by hboutemy** [comment]
closing, superceeded by #914

**Comment by fpapon** [comment]
> FYI, running
> 
> ```
> bin/add-new-release.sh content/io/yupiik/maven/plugin/yupiik-tools-maven-plugin-1.2.4.buildspec 1.2.5
> ```
> 
> prepares the new buildspec and gives you commands to copy/paste to create branch and PR
> 
> the PR will contain a link to https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/yupiik/maven/plugin/README.md which helps tracking if the new release is better or worse that the previous one
> 
> and "cherry on the cake" :) if your project's latest release, I do the new rebuild systematically without any request from the project
> 
> when the latest release is not fully reproducible, I crebuild the new release only when I decide (because I think it's worth it), a little bit later than the new releases of fully reproducible projects

Very nice, thanks :)

**Pull request closed without merging**
