### PR TITLE
Provide badge status for projects

### PR DESCRIPTION
**Pull request by jskov**
This PR provides a suggested fix for #79

If the bash-fu is not optimal for your style, please adapt as you see fit.

You may want to tweak the message so it includes Reproducible Builds or something.
Entirely up to you.

I must admit I did not spend enough time to determine if it is possible to merge a "standard" badge with the endpoint magic.

The provided `badge-status.json` file can be used similar to this: 

```text
https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjvm-repo-rebuild%2Freproducible-central%2Fmaster%2Fcontent%2F...path to project directory...%2Fbadge-status.json
```

### CODE REVIEW

**Comment by hboutemy** [comment]
reviewing, adding a few pointers and ideas:
- shields.io documentation on endpoint badge: https://shields.io/badges/endpoint-badge
- documentation on the Reproducible Central badge: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/doc/TOOLS.md#4-add-reproducible-builds-badge-to-a-project-with-reproducible-releases

idea: instead of jus a flag ok/ko for the badge, having a summary `3/3` when there are 3 reproduced files on 3 output, or `2/3` when one output is not ok could make the result more appealing and useful even when a project is not 100% reproducible

**Comment by hboutemy** [comment]
another idea: add the badge to README.md, for example in the title instead of "RB check"

**Comment by hboutemy** [comment]
I reworked the current PR into #191, now merged and badge visible in every README.md

thanks a lot for your help on this; I did not merge the PR itself, but your exemple helped me so much to define the badge that I hope will help projects know their situation and enhance over time

again, thanks a lot

**Comment by jskov** [comment]
Nice, thanks!
I will be updating my projects.

**Pull request closed without merging**
